# 日志项配置
log:
  # 是否每次启动新建log文件
  force-new: false
  # 日志等级
  #   trace debug info warn error
  level: "debug"
  # 日志存活时间，到期新建log文件
  aging: 24h
  # 是否开启控制台颜色
  colorful: true

# API 配置
api:
  # 监听地址
  host: "0.0.0.0"
  # 绑定端口
  port: 8080

# Elasticsearch 配置
es:
  url: "http://192.168.3.7:9200"