/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LayBody: typeof import('@layui/layui-vue')['LayBody']
    LayFooter: typeof import('@layui/layui-vue')['LayFooter']
    LayHeader: typeof import('@layui/layui-vue')['LayHeader']
    LayLayout: typeof import('@layui/layui-vue')['LayLayout']
    LayMenu: typeof import('@layui/layui-vue')['LayMenu']
    LayMenuItem: typeof import('@layui/layui-vue')['LayMenuItem']
    LaySide: typeof import('@layui/layui-vue')['LaySide']
    LaySubMenu: typeof import('@layui/layui-vue')['LaySubMenu']
    LaySwitch: typeof import('@layui/layui-vue')['LaySwitch']
    Side: typeof import('./src/components/Side.vue')['default']
  }
}
